### ISSUE TITLE
能不能出个sqlite的版本?

### ISSUE THREAD

**Issue by jsyzjhj** [lanmeng-org/LMArticle#1]
能不能出个sqlite的版本?

**Comment by lanmeng-org** [comment]
现在是支持 sqlite 数据库的，composer install 之后，把`.env`文件中的数据库配置替换成如下配置即可
```
DB_CONNECTION=sqlite
DB_DATABASE=sqlite文件路径
```

**Comment by jsyzjhj** [comment]
windows下如何安装？谢谢

**Comment by lanmeng-org** [comment]
先安装 windows版的composer, 然后按照 readme.md 里执行相关命令就行了。

**Comment by jsyzjhj** [comment]
太复杂。没装上。没有直接配置下数据库就能用的么？

**Comment by lanmeng-org** [comment]
暂时没有直接改下配置就能用的, 后面准备写的Golang版的, 可以修改下配置就能用.
